### ISSUE TITLE
how to create a new task

### ISSUE THREAD

**Issue by docooler** [jakecoffman/gorunner#19]
Hi There:

I'm very glade to see you do a good job. but when i run this program on my laptop I didn't find the way to create a new task. all button has no response. could you give me a simple guide. I'm not good at front end . But I think I'm good at golang programming. So I want to contribute on this project. Is there any of TO List? or something else. At first I want to move the backend code to Beego which is a golang framework.Do you have any suggestion or comments?

**Comment by jakecoffman** [comment]
I just tried and had the same issue but then rebuilt and it seems to be working again. I can look at this tonight (in about 8 hours from now) because it does seem to be a problem.

This project was a prototype that I decided not to finish but if you want to rewrite in Beego I would be happy to collaborate with you and work on the frontend. Maybe you can work on a fork and when it can replace the current backend you can send a pull request? I can write some features out tonight.

**Comment by hashrock** [comment]
Same issue here.
I tried to rollback this commit, then it works.
https://github.com/jakecoffman/gorunner/commit/d28c558aab7ff7a09873e6f1a948734df8dc920e
